-- NOTE: This file is auto generated by ./sql-generator

-- FootprintRepository.getAssetsToAssign
select
  "asset_exif"."assetId",
  "asset_exif"."latitude",
  "asset_exif"."longitude"
from
  "asset_exif"
  left join "asset_region" on "asset_region"."assetId" = "asset_exif"."assetId"
where
  "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null
  and (
    "asset_region"."assetId" is null
    or "asset_region"."version" != $1
    or "asset_region"."latitude" != "asset_exif"."latitude"
    or "asset_region"."longitude" != "asset_exif"."longitude"
  )
limit
  $2

-- FootprintRepository.deleteUnlocated
delete from "asset_region"
where
  not exists (
    select
    from
      "asset_exif"
    where
      "asset_exif"."assetId" = "asset_region"."assetId"
      and "asset_exif"."latitude" is not null
      and "asset_exif"."longitude" is not null
  )
