-- NOTE: This file is auto generated by ./sql-generator

-- LocateRepository.getUnlocatedAssets
select
  "asset"."id",
  "asset"."localDateTime"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ($2, $3)
  and "asset_exif"."latitude" is null
  and "asset_exif"."make" is not null
  and not exists (
    select
    from
      "asset_metadata"
    where
      "asset_metadata"."assetId" = "asset"."id"
      and "asset_metadata"."key" = $4
  )
order by
  "asset"."localDateTime",
  "asset"."id"

-- LocateRepository.getAssets
select
  "asset"."id",
  "asset"."localDateTime",
  "asset"."originalPath"
from
  "asset"
where
  "asset"."ownerId" = $1
  and "asset"."id" in ($2)

-- LocateRepository.getLocatedInDirectories
select
  "asset_exif"."latitude",
  "asset_exif"."longitude"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null
  and regexp_replace("asset"."originalPath", '/[^/]*$', '') in ($2)
limit
  $3

-- LocateRepository.getNearestLocated
select
  "asset_exif"."latitude",
  "asset_exif"."longitude"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null
  and "asset"."localDateTime" >= $2
  and "asset"."localDateTime" <= $3
order by
  abs(
    extract(
      epoch
      from
        ("asset"."localDateTime" - $4::timestamptz)
    )
  )
limit
  $5

-- LocateRepository.ignore
insert into
  "asset_metadata" ("assetId", "key", "value")
values
  ($1, $2, $3)
on conflict ("assetId", "key") do nothing
