-- NOTE: This file is auto generated by ./sql-generator

-- LocateRepository.getUnlocatedAssets
select
  "asset"."id",
  "asset"."localDateTime"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ($2, $3)
  and "asset_exif"."latitude" is null
  and "asset_exif"."make" is not null
  and not exists (
    select
    from
      "asset_metadata"
    where
      "asset_metadata"."assetId" = "asset"."id"
      and "asset_metadata"."key" = $4
  )
order by
  "asset"."localDateTime",
  "asset"."id"

-- LocateRepository.getAssets
select
  "asset"."id",
  "asset"."localDateTime",
  "asset"."originalPath"
from
  "asset"
where
  "asset"."ownerId" = $1
  and "asset"."id" in ($2)

-- LocateRepository.getLocatedInDirectories
select
  "asset_exif"."latitude",
  "asset_exif"."longitude"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null
  and regexp_replace("asset"."originalPath", '/[^/]*$', '') in ($2)
limit
  $3

-- LocateRepository.getNearestLocated
select
  "asset_exif"."latitude",
  "asset_exif"."longitude"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset_exif"."latitude" is not null
  and "asset_exif"."longitude" is not null
  and "asset"."localDateTime" >= $2
  and "asset"."localDateTime" <= $3
order by
  abs(
    extract(
      epoch
      from
        ("asset"."localDateTime" - $4::timestamptz)
    )
  )
limit
  $5

-- LocateRepository.ignore
insert into
  "asset_metadata" ("assetId", "key", "value")
values
  ($1, $2, $3)
on conflict ("assetId", "key") do nothing

-- LocateRepository.getSuspects
select
  "asset"."id" as "assetId",
  "asset"."localDateTime",
  "asset_exif"."latitude",
  "asset_exif"."longitude",
  "asset_exif"."city",
  "asset_exif"."country",
  "other"."id" as "otherAssetId",
  "other"."localDateTime" as "otherLocalDateTime",
  "otherExif"."latitude" as "otherLatitude",
  "otherExif"."longitude" as "otherLongitude",
  "otherExif"."city" as "otherCity",
  "otherExif"."country" as "otherCountry"
from
  "asset_metadata"
  inner join "asset" on "asset"."id" = "asset_metadata"."assetId"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
  inner join "asset" as "other" on "other"."id" = ("asset_metadata"."value" ->> 'otherAssetId')::uuid
  inner join "asset_exif" as "otherExif" on "otherExif"."assetId" = "other"."id"
where
  "asset_metadata"."key" = $1
  and "asset"."ownerId" = $2
  and "asset"."deletedAt" is null
  and "other"."deletedAt" is null
  and "asset_exif"."latitude" is not null
  and "otherExif"."latitude" is not null
order by
  "asset"."localDateTime",
  "asset"."id"

-- LocateRepository.confirmSuspects
begin
insert into
  "asset_metadata" ("assetId", "key", "value")
values
  ($1, $2, $3)
on conflict ("assetId", "key") do nothing
rollback

-- LocateRepository.clearSuspects
delete from "asset_metadata"
where
  "key" = $1
  and "assetId" in ($2)
