-- NOTE: This file is auto generated by ./sql-generator

-- ReorganizeRepository.getFolderAssets
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."libraryId",
  "library"."ownerId" as "libraryOwnerId",
  "asset"."originalPath",
  "asset"."localDateTime",
  "asset"."isOffline",
  "asset"."deletedAt",
  "asset_job_status"."dateFromExif",
  "video"."id" as "videoId",
  "video"."originalPath" as "videoPath",
  "video"."isExternal" as "videoIsExternal",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $1
    limit
      $2
  ) as "sidecarPath"
from
  "asset"
  left join "library" on "library"."id" = "asset"."libraryId"
  left join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
  left join "asset" as "video" on "video"."id" = "asset"."livePhotoVideoId"
where
  not exists (
    select
      "photo"."id"
    from
      "asset" as "photo"
    where
      "photo"."livePhotoVideoId" = "asset"."id"
  )
  and starts_with(asset."originalPath", $3)
order by
  "asset"."originalPath"

-- ReorganizeRepository.getAlbumAssets
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."libraryId",
  "library"."ownerId" as "libraryOwnerId",
  "asset"."originalPath",
  "asset"."localDateTime",
  "asset"."isOffline",
  "asset"."deletedAt",
  "asset_job_status"."dateFromExif",
  "video"."id" as "videoId",
  "video"."originalPath" as "videoPath",
  "video"."isExternal" as "videoIsExternal",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $1
    limit
      $2
  ) as "sidecarPath"
from
  "asset"
  left join "library" on "library"."id" = "asset"."libraryId"
  left join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
  left join "asset" as "video" on "video"."id" = "asset"."livePhotoVideoId"
  inner join "album_asset" on "album_asset"."assetId" = "asset"."id"
where
  not exists (
    select
      "photo"."id"
    from
      "asset" as "photo"
    where
      "photo"."livePhotoVideoId" = "asset"."id"
  )
  and "album_asset"."albumId" = $3::uuid
order by
  "asset"."originalPath"

-- ReorganizeRepository.get
select
  *
from
  "reorganization"
where
  "id" = $1::uuid

-- ReorganizeRepository.getAll
select
  *
from
  "reorganization"
where
  "ownerId" = $1::uuid
order by
  "createdAt" desc

-- ReorganizeRepository.getActive
select
  *
from
  "reorganization"
where
  "status" in ($1, $2)

-- ReorganizeRepository.getItemCounts
select
  "reorganizationId",
  "status",
  "reason",
  count(*) as "count"
from
  "reorganization_item"
where
  "reorganizationId" in ($1)
group by
  "reorganizationId",
  "status",
  "reason"

-- ReorganizeRepository.getItems
select
  *
from
  "reorganization_item"
where
  "reorganizationId" = $1::uuid
  and "status" in ($2)
order by
  "position" asc
limit
  $3

-- ReorganizeRepository.transition
update "reorganization"
set
  "status" = $1
where
  "id" = $2::uuid
  and "status" = $3
returning
  *

-- ReorganizeRepository.updateItemStatuses
update "reorganization_item"
set
  "status" = $1,
  "error" = $2
where
  "reorganizationId" = $3::uuid
  and "status" in ($4)

-- ReorganizeRepository.interruptRunning
update "reorganization"
set
  "status" = $1,
  "cancelRequested" = $2
where
  "status" = $3
returning
  *

-- ReorganizeRepository.retryStayed
update "reorganization_item"
set
  "status" = $1,
  "reason" = $2,
  "error" = $3
where
  "reorganizationId" = $4::uuid
  and "status" = $5
  and "toPath" is not null
  and "assetId" is not null

-- ReorganizeRepository.isUsedByAnother
select
  "id"
from
  "asset"
where
  "originalPath" = $1
  and "id" != $2::uuid
limit
  $3
select
  "id"
from
  "asset_file"
where
  "path" = $1
  and "assetId" != $2::uuid
limit
  $3

-- ReorganizeRepository.getAssetState
select
  "asset"."id",
  "asset"."originalPath",
  "asset"."libraryId",
  "asset"."isOffline",
  "asset"."deletedAt",
  "asset"."livePhotoVideoId",
  "video"."isExternal" as "videoIsExternal",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $1
    limit
      $2
  ) as "sidecarPath"
from
  "asset"
  left join "asset" as "video" on "video"."id" = "asset"."livePhotoVideoId"
where
  "asset"."id" = $3::uuid
