-- NOTE: This file is auto generated by ./sql-generator

-- ReorganizeRepository.getFolderAssets
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."libraryId",
  "library"."ownerId" as "libraryOwnerId",
  "asset"."originalPath",
  "asset"."localDateTime",
  "asset"."isOffline",
  "asset"."deletedAt",
  "asset_job_status"."dateFromExif",
  "video"."id" as "videoId",
  "video"."originalPath" as "videoPath",
  "video"."isExternal" as "videoIsExternal",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $1
    limit
      $2
  ) as "sidecarPath"
from
  "asset"
  left join "library" on "library"."id" = "asset"."libraryId"
  left join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
  left join "asset" as "video" on "video"."id" = "asset"."livePhotoVideoId"
where
  not exists (
    select
      "photo"."id"
    from
      "asset" as "photo"
    where
      "photo"."livePhotoVideoId" = "asset"."id"
  )
  and starts_with(asset."originalPath", $3)
order by
  "asset"."originalPath"

-- ReorganizeRepository.getAlbumAssets
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."libraryId",
  "library"."ownerId" as "libraryOwnerId",
  "asset"."originalPath",
  "asset"."localDateTime",
  "asset"."isOffline",
  "asset"."deletedAt",
  "asset_job_status"."dateFromExif",
  "video"."id" as "videoId",
  "video"."originalPath" as "videoPath",
  "video"."isExternal" as "videoIsExternal",
  (
    select
      "asset_file"."path"
    from
      "asset_file"
    where
      "asset_file"."assetId" = "asset"."id"
      and "asset_file"."type" = $1
    limit
      $2
  ) as "sidecarPath"
from
  "asset"
  left join "library" on "library"."id" = "asset"."libraryId"
  left join "asset_job_status" on "asset_job_status"."assetId" = "asset"."id"
  left join "asset" as "video" on "video"."id" = "asset"."livePhotoVideoId"
  inner join "album_asset" on "album_asset"."assetId" = "asset"."id"
where
  not exists (
    select
      "photo"."id"
    from
      "asset" as "photo"
    where
      "photo"."livePhotoVideoId" = "asset"."id"
  )
  and "album_asset"."albumId" = $3::uuid
order by
  "asset"."originalPath"
