-- NOTE: This file is auto generated by ./sql-generator

-- TripRepository.getByOwnerId
select
  "trip".*,
  "album"."albumName"
from
  "trip"
  left join "album" on "album"."id" = "trip"."albumId"
where
  "trip"."ownerId" = $1
order by
  "trip"."startAt"

-- TripRepository.create
insert into
  "trip" ("ownerId")
values
  ($1)
returning
  *

-- TripRepository.update
update "trip"
set
  "generatedName" = $1
where
  "id" = $2

-- TripRepository.getAssets
select
  "asset"."id",
  "asset"."localDateTime",
  "asset"."createdAt",
  "asset"."originalFileName",
  "asset_exif"."latitude",
  "asset_exif"."longitude",
  "asset_exif"."make"
from
  "asset"
  inner join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and "asset"."visibility" in ($2, $3)
order by
  "asset"."localDateTime"

-- TripRepository.getPlaces
select
  point.index,
  place."countryCode",
  place."admin1Name",
  place."admin2Name"
from
  unnest($1::double precision[], $2::double precision[]) with ordinality as point(latitude, longitude, index)
  cross join lateral (
    select
      "countryCode",
      "admin1Name",
      "admin2Name"
    from
      geodata_places
    where
      earth_box (
        ll_to_earth_public (point.latitude, point.longitude),
        $3
      ) @> ll_to_earth_public (geodata_places.latitude, geodata_places.longitude)
    order by
      earth_distance (
        ll_to_earth_public (point.latitude, point.longitude),
        ll_to_earth_public (geodata_places.latitude, geodata_places.longitude)
      )
    limit
      1
  ) as place

-- TripRepository.getAlternateNames
select distinct
  on ("name", "admin1Name") "name",
  "admin1Name",
  "alternateNames"
from
  "geodata_places"
where
  (
    "name" = $1
    and "admin1Name" = $2
  )
order by
  "name",
  "admin1Name",
  length("alternateNames") desc nulls last
